### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by rukaelin** [hyperwallet/php-sdk#21]
We are using your SDK and at the mentioned line, a null pointer exception occurred. 
`$errorResponse[0]` is null, so calling a method on it fails.

https://github.com/hyperwallet/php-sdk/blob/839ce3cc0843b89842706489801d82dd1ceee3fb/src/Hyperwallet/Exception/HyperwalletApiException.php#L33

here is the stack trace:
```
Uncaught Error: Call to a member function getMessage() on null in ***/vendor/hyperwallet/sdk/src/Hyperwallet/Exception/HyperwalletApiException.php:26
Stack trace:
#0 ***/vendor/hyperwallet/sdk/src/Hyperwallet/Util/ApiClient.php(145): Hyperwallet\Exception\HyperwalletApiException->__construct(Object(Hyperwallet\Response\ErrorResponse), Object(GuzzleHttp\Exception\ServerException))
#1 ***/vendor/hyperwallet/sdk/src/Hyperwallet/Util/ApiClient.php(107): Hyperwallet\Util\ApiClient->doRequest('GET', '/rest/v3/transf...', Array, Array)
#2 ***/vendor/hyperwallet/sdk/src/Hyperwallet/Hyperwallet.php(1347): Hyperwallet\Util\ApiClient->doGet('/rest/v3/transf...', Array, Array)
#3
```

**Comment by wmews-hw** [comment]
Hi @rukaelin,

We could simply add a null check to avoid the error but could you help us understand the scenario providing:
- what is the call that we are trying to make?
- what was the http response that is causing this error?

**Comment by rukaelin** [comment]
It's harder for me to tell, as it happened already more than two weeks in the past.
I think it relates to a 502 response that was sent shortly before the mentioned error:

file: gyg/vendor/hyperwallet/sdk/src/Hyperwallet/Response/ErrorResponse.php:37

msg: Undefined index: errors
context: 
(
    [statusCode] => 502
    [errors] => array((
    [error] => array((
    [message] => "Bad Gateway: indicates that the server, while acting as a gateway or proxy, received an invalid response from an inbound server it accessed while attempting to fulfill the request."
    [code] => "502"
)
)
)
)
)
